##
## Section: Application Configuration
## Event Bus configurations
##

# Override the default destination for PDF requests
pdf.eventbus.destination.requests=custom-pdf-requests-destination
%test.pdf.eventbus.destination.requests=custom-pdf-requests-destination-test

# Override the default destination for PDF completed events
pdf.eventbus.destination.completed=custom-pdf-completed-destination
%test.pdf.eventbus.destination.completed=custom-pdf-completed-destination-test

# PDF Generation Error Destination
pdf.eventbus.destination.errors=custom-pdf-errors-destination
%test.pdf.eventbus.destination.errors=custom-pdf-errors-destination-test

##
## Section: PDF Generation Configuration
## PDF generation settings
##

# Setting the delay for PDF generation
pdf.generation.delay.min-seconds=3
pdf.generation.delay.max-seconds=10

# Setting the delay for PDF generation in tests
%test.pdf.generation.delay.min-seconds=3
%test.pdf.generation.delay.max-seconds=3

# Setting the output path for generated PDFs
# This path is relative to the target directory
pdf.generation.output.path=target/pdf-generated

# MinIO Configuration
#quarkus.minio.host=http://localhost:9000
#quarkus.minio.access-key=minioadmin
#quarkus.minio.secret-key=minioadmin

# Custom property for bucket name
pdf.minio.bucket-name=pdf-bucket

##
## Section: Logging Configuration
## Logging settings for the application
##
quarkus.log.category."it.dontesta.quarkus.sse".level=DEBUG
quarkus.log.category."org.apache.fop".level=ERROR
quarkus.log.category."org.fugerit.java".level=ERROR

##
## This section configure the OpenShift extension
## For more info see https://quarkus.io/guides/deploying-to-openshift
##

# If true, the service will be exposed outside the cluster
# and will be assigned a route.
# If false, the service will only be accessible within the cluster (default)
quarkus.openshift.route.expose=true

# The target named port. If not provided, it will be deducted
# from the Service resource ports. Options are: "http" and "https".
quarkus.openshift.route.target-port=http

## Route TLS configuration:
# The termination type of the route. Options are: "edge",
# "reencrypt", and "passthrough".
quarkus.openshift.route.tls.termination=edge

# The desired behavior for insecure connections to a route.
quarkus.openshift.route.tls.insecure-edge-termination-policy=None

# The name of the Secret that contains the database URL (that will be contained the username and password)
# and the application keystore password.
quarkus.openshift.env.secrets=minio-access-key

# Define the number of replicas for the deployment
quarkus.openshift.replicas=2

# The base image to be used when a container image is being produced for the jar build.
# The value of this property is used to create an ImageStream for the builder image used in
# the Openshift build. When it references images already available in the internal Openshift
# registry, the corresponding streams are used instead. When the application is built against
# Java 21 or higher.
#quarkus.openshift.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21:1.20-2.1729773471
#quarkus.openshift.base-jvm-image=registry.redhat.io/ubi9/openjdk-21:1.21-3.1736923862

# The base image to be used when a container image is being produced for the native build.
#quarkus.openshift.base-native-image=quay.io/quarkus/ubi-quarkus-native-binary-s2i:2.0

# The builder image to be used when a container image is being produced for the jar build.
# The value of this property is used to create an ImageStream for the builder image used in
# the Openshift build. When it references images already available in the internal Openshift
# registry, the corresponding streams are used instead.
# If you want use the Podman to build the container image, you can use the podman as value for this property and in this
# case you need have the quarkus-container-image-podman extension installed.
# For more info see https://quarkus.io/guides/container-image#podman
quarkus.container-image.builder=openshift

# MinIO configuration (production)
%prod.quarkus.minio.host=http://minio
%prod.quarkus.minio.port=9000
%prod.quarkus.minio.secure=false
%prod.quarkus.minio.access-key=${MINIO_USER_ACCESS_KEY}
%prod.quarkus.minio.secret-key=${MINIO_USER_SECRET_KEY}

# Redis configuration (production)
%prod.quarkus.redis.hosts=redis://redis:6379
%prod.quarkus.redis.password=${DATABASE_PASSWORD}