apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: antonio-musarra-dev
  labels:
    app: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      volumes:
        - name: redis-data
          emptyDir: {}
      containers:
        - name: redis
          # Immagine ufficiale RHEL 9 specifica indicata da te
          image: registry.redhat.io/rhel9/redis-7:9.8-1782346713
          args:
            - redis-server
            - --save
            - ""
            - --appendonly
            - "no"
            # Forziamo Redis a usare la password iniettata dall'ambiente
            - --requirepass
            - "$(REDIS_PASSWORD)"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
          env:
            # L'entrypoint Red Hat usa questa variabile per configurare la sicurezza all'avvio
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: database-password
          volumeMounts:
            # La path standard di persistenza per l'immagine Red Hat
            - name: redis-data
              mountPath: /var/lib/redis/data
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - 'test "$(redis-cli -h 127.0.0.1 -a "$REDIS_PASSWORD" ping)" == "PONG"'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler